### ISSUE TITLE
Instances remains empty

### ISSUE THREAD

**Issue by albundy83** [outscale/cloud-provider-osc#318]
Hello here the description:

**What happened**:
When I tag a Service with correct details, LoadBalancer is created but Instances are not filled

**What you expected to happen**:
Filled Instances

**How to reproduce it (as minimally and precisely as possible)**:
Use terraform from here https://github.com/outscale/osc-k8s-rke-cluster to create infrastructures cloudgouv-eu-west-1 zone (I do not deploy rke1)
Deploy a cluster using https://github.com/lablabs/ansible-role-rke2 on this infrastructure
Allow NAT IP address in apiaccessrule to allow cloud-provider-osc to connect

**Anything else we need to know?**:

**Environment**:
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.11", GitCommit:"8cfcba0b15c343a8dc48567a74c29ec4844e0b9e", GitTreeState:"clean", BuildDate:"2023-06-14T09:57:26Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.11+rke2r1", GitCommit:"8cfcba0b15c343a8dc48567a74c29ec4844e0b9e", GitTreeState:"clean", BuildDate:"2023-06-14T21:31:34Z", GoVersion:"go1.19.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: RKE2 using https://github.com/lablabs/ansible-role-rke2
- OS (e.g. from /etc/os-release): Ubuntu 22.04 fully updated
- Kernel (e.g. `uname -a`): Linux ip-10-0-1-10 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

/kind bug

**Comment by albundy83** [comment]
I have the full logs if you need it but I have found only this message strange:
```
I0706 18:14:54.939744       1 tags.go:153] clusterTagKey()
W0706 18:14:54.939756       1 instances.go:113] node "ip-10-0-1-21.cloudgouv-eu-west-1.compute.internal" did not have ProviderID set
W0706 18:14:54.939785       1 instances.go:113] node "ip-10-0-1-22.cloudgouv-eu-west-1.compute.internal" did not have ProviderID set
W0706 18:14:54.939790       1 instances.go:113] node "ip-10-0-1-24.cloudgouv-eu-west-1.compute.internal" did not have ProviderID set
W0706 18:14:54.939794       1 instances.go:113] node "ip-10-0-1-12.cloudgouv-eu-west-1.compute.internal" did not have ProviderID set
W0706 18:14:54.939805       1 instances.go:113] node "ip-10-0-1-20.cloudgouv-eu-west-1.compute.internal" did not have ProviderID set
W0706 18:14:54.939809       1 instances.go:113] node "ip-10-0-1-19.cloudgouv-eu-west-1.compute.internal" did not have ProviderID set
W0706 18:14:54.939833       1 instances.go:113] node "ip-10-0-1-23.cloudgouv-eu-west-1.compute.internal" did not have ProviderID set
W0706 18:14:54.939841       1 instances.go:113] node "ip-10-0-1-10.cloudgouv-eu-west-1.compute.internal" did not have ProviderID set
W0706 18:14:54.939845       1 instances.go:113] node "ip-10-0-1-11.cloudgouv-eu-west-1.compute.internal" did not have ProviderID set
```

**Comment by outscale-vbr** [comment]
Hello @albundy83,

We have been able to test rke2 with cloud-provider-osc.

To make it work the CCM needs to be install directly by doing this:

* Put in your /etc/rancher/rke2/config.yaml:
      cloud-provider-name: external

* Set all the required tags for Outscale Resource [1]

* Watch out that OscK8sNodeName value must be the same as kubernetes.io/host so it can be for your example:
      OscK8sNodeName=ip-10-0-1-21.cloudgouv-eu-west-1.compute.internal

* Add a file in /var/lib/rancher/rke2/server/manifests/secrets.yaml (https://docs.rke2.io/helm) containing:
apiVersion: v1
kind: Secret
metadata:
  name: osc-secret
  namespace: kube-system
stringData:
  key_id: OSC_ACCESS_KEY 
  access_key: OSC_SECRET_KEY 
  aws_default_region: eu-west-2
  aws_availability_zones: MY_AWS_AVAILABILITY_ZONES
  osc_account_id: MY_OSC_ACCOUNT_ID
  osc_account_iam: MY_OSC_ACCOUNT_IAM
  osc_user_id: MY_OSC_USER_ID
  osc_arn: MY_OSC_ARN

Replace  OSC_ACCESS_KEY and OSC_SECRET_KEY with your access_key and secret_key  :
  
* Add a file  in  /var/lib/rancher/rke2/server/manifests/cloud-provider-osc.yaml  containing:
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ccm
  namespace: kube-system
spec:
  chart: https://github.com/outscale-dev/cloud-provider-osc/releases/download/v0.2.0/osc-cloud-controller-manager-0.2.0.tgz
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule 
        operator: Exists 
      - key: node-role.kubernetes.io/etcd
        effect: NoExecute

After deployment of the cluster,you will have a providerId available for each node

./kubectl describe node ip-10-0-1-21.cloudgouv-eu-west-1.compute.internal | grep ProviderID
    ProviderID: aws:///eu-west-2a/i-e7590973

You can use this example to validate cloud-provider-osc with your platform: https://github.com/outscale/cloud-provider-osc/tree/OSC-MIGRATION/examples/2048 

[1] https://github.com/outscale/cloud-provider-osc/blob/f0f87778379d50816850cf6f7cdeb933d161fdaa/deploy/README.md

**Comment by albundy83** [comment]
Hello,
It has worked perfectly as I use terraform from here https://github.com/outscale/osc-k8s-rke-cluster , tags on Instances were already correct.
The real trick was `cloud-provider-name: external`

Thanks a lot !!
