### ISSUE TITLE
Load Balancer not adding back end VMs with RKE2 cluster

### ISSUE THREAD

**Issue by acabrele** [outscale/cloud-provider-osc#338]
**What happened**:
When provisioning a load balancer the back end VMs are not added.  The CCM reports an error:
`{"Errors":[{"Type":"InvalidParameterValue","Details":"The provided value 'xxx' does not respect the expected ID prefix 'i-'.","Code":"4104"}],"ResponseContext":{"RequestId":"1a76d260-c993-417a-8d54-5a0c06a5e6a8"}}`

This seems to be because the spec.providerID is set to rke2://<node pool name> rather than the instance id (which I think RKE1 does).  CCM then extracts this and uses it as the VmID filter here https://github.com/outscale/cloud-provider-osc/blob/4e8b07ac13c3f27dde7a4df6471a5703ea43b914/cloud-controller-manager/osc/instances_v2.go#L134

**What you expected to happen**:
Backend VMs added to LB

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy rancher server 2.8.0
- Enable the outscale node driver
- Deploy an RKE2 cluster on outscale
- Deploy the CCM in the RKE2 cluster
- Try to create a load balancer

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.27
- Cloud provider or hardware configuration: Outscale
- OS (e.g. from /etc/os-release): Ubuntu 22.04 (rke2 vms)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

**Comment by outscale-mdr** [comment]
Hello @acabrele,

The fact that the `providerId` is  set to `rke2://` is a problem to retrieve the InstanceId. Can you deploy the CCM during the rke2 cluster creation and not after ?

You can found the help to do it in this thread: https://github.com/outscale/cloud-provider-osc/issues/318#issuecomment-1633741701

Tell us if it helps.

We will investiguate how to detect it earlier.

Thank you,
Best regards,
Maxime

**Comment by acabrele** [comment]
Thanks @outscale-mdr.  I had made a small change to instances_v2.go, but installing the CCM during rke2 deployment works.  Here is the terraform rancher2_cluster_v2 that works for me:

`
...
  rke_config {
...
    machine_selector_config {
      config = <<EOF
cloud-provider-name: "external"
disable-cloud-controller: true
EOF
    }
...
    additional_manifest = <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: osc-ccm-secret
  namespace: kube-system
stringData:
  key_id: "${var.access_key_id}" 
  access_key: "${var.secret_key_id}" 
  aws_default_region: "${var.region}"
  aws_availability_zones: MY_AWS_AVAILABILITY_ZONES
  osc_account_id: MY_OSC_ACCOUNT_ID
  osc_account_iam: MY_OSC_ACCOUNT_IAM
  osc_user_id: MY_OSC_USER_ID
  osc_arn: MY_OSC_ARN
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ccm
  namespace: kube-system
spec:
  chart: https://github.com/outscale/cloud-provider-osc/releases/download/v${var.ccm_version}/osc-cloud-controller-manager-${var.ccm_version}.tgz
  targetNamespace: kube-system
  bootstrap: true
  valuesContent: |-
    oscSecretName: osc-ccm-secret
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule 
        operator: Exists 
      - key: node-role.kubernetes.io/etcd
        effect: NoExecute

EOF
  }
...
`
