### ISSUE TITLE
Load balancer internet facing in private subnet

### ISSUE THREAD

**Issue by nym4xx** [outscale/cloud-provider-osc#344]
I have a k8s cluster with its nodes in a network with a private subnet. First of all, I created a load balancer for the API server with Terraform and I have no problem accessing the API server with the load balancer's public IP address. In cockpit the loadbalancer is attached to the subnet and the vms are attached to the loadbalancer. Secondly, I installed osc-cloud-provider and marked the network, subnet, security group and VMS with the cluster ID and node name for the VMS. I then tested with a load balancer service with lb's simple example: the load balancer is created by osc-cloud-provider and the external IP address was set with the hostname of the load balancer in the ingress controller service. But this doesn't work: in cockpit, the load balancer is not attached to the private subnet network and it has no vms attached. It appears that the osc-cloud-provider is not able to define the network for the load balancer.

**Comment by outscale-mdr** [comment]
Hello @nym4xx,

Thank you for reporting an issue. To be able to treat this issue, could you fill the bug form ?

```
<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!-->


**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

<!-- DO NOT EDIT BELOW THIS LINE -->
/kind bug
```

**Comment by outscale-hmi** [comment]
Hi @nym4xx,

Thank you for reaching out.

You can find a debug tree that can help you troubleshoot your issue at the following link: [Debug Tree](https://github.com/outscale/cloud-provider-osc/tree/OSC-MIGRATION/deploy).

Please review the debug tree to see if it addresses your problem. If you continue to experience issues, feel free to reopen this issue, and we'll be happy to assist further.

Best regards,
