### ISSUE TITLE
Support kubernetes 1.27 and/or update matrix compatibility

### ISSUE THREAD

**Issue by pierreozoux** [outscale/cloud-provider-osc#345]
Hi!

kubernetes 1.26 is almost EOL.

Could you update this piece of doc:
https://github.com/outscale/cloud-provider-osc/blob/OSC-MIGRATION/deploy/README.md#prerequisites
(and/or relevant code)

Thanks for your work!

**Comment by outscale-hmi** [comment]
https://github.com/outscale/cloud-provider-osc/pull/357
