### ISSUE TITLE
Debug Tree for Users

### ISSUE THREAD

**Issue by outscale-mdr** [outscale/cloud-provider-osc#349]
Hello team,

Here is a draft of Debug tree for users.

Could you test if it is correct and add it to the Doc ?
![DebugTree](https://github.com/outscale/cloud-provider-osc/assets/91073311/05010104-1cb4-4466-8a68-75b734a7e703)

**Comment by outscale-hmi** [comment]
Hello, 
I tried to validate the tree debug process, Can you check if it's OK to be added to the documentation  
![Flowcharts (1)](https://github.com/outscale/cloud-provider-osc/assets/56728382/39f7f352-9600-4678-a5de-0918773d2b4d)
