### ISSUE TITLE
Remove default value for imagePullSecrets

### ISSUE THREAD

**Issue by albundy83** [outscale/cloud-provider-osc#358]
Hello,

can you remove the default value for the imagePullSecrets which is here:
https://github.com/outscale/cloud-provider-osc/blob/OSC-MIGRATION/deploy/k8s-osc-ccm/templates/osc-ccm.yaml#L138

As if we don't use it, we have Events complaining about missing Secret.

Thanks a lot :)

/kind bug

**Comment by albundy83** [comment]
Hello,

here the repeating message from Kubernetes Events "Unable to retrieve some image pull secrets (registry-dockerconfigjson); attempting to pull the image may not succeed."

**Comment by albundy83** [comment]
Hello,

will you release a new version soon ?

**Comment by outscale-hmi** [comment]
Release done

**Comment by albundy83** [comment]
It works perfectly
