### ISSUE TITLE
Bug with the vpn connection

### ISSUE THREAD

**Issue by naicoram01** [outscale/cloud-provider-osc#367]
Hi,

I have this error when trying to create a vpn connection.

The VPN connection will create :
      - New Client GW 
      - VPN connection based on a Virtual GW used already with another Client GW

Could you please help ?

Thank you so much

│ Error: Plugin did not respond
│
│   with outscale_vpn_connection.VPN_Secours-NET-TEST,
│   on vpn-net-test.tf line 78, in resource "outscale_vpn_connection" "VPN_Secours-NET-TEST":
│   78: resource "outscale_vpn_connection" "VPN_Secours-NET-TEST" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-outscale_v0.10.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x111922f]

goroutine 85 [running]:
github.com/terraform-providers/terraform-provider-outscale/outscale.vpnConnectionRefreshFunc.func1()
        /src/github.com/terraform-providers/terraform-provider-outscale/outscale/resource_outscale_vpn_connection.go:277 +0x16f
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1()
        /root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/resource/state.go:103 +0x186
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
        /root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/resource/state.go:80 +0x1b8

Error: The terraform-provider-outscale_v0.10.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by naicoram01** [comment]
for information : 
// ###===VPN SECOURS====###
resource "outscale_client_gateway" "CGW_Celeste-NET-TEST" {
    bgp_asn         = 2551
    public_ip       = "82.210.16.178"
    connection_type = "ipsec.1"
        tags {
                key   = "Name"
                value = "CGW_Celeste-NET-TEST"
        }
}

resource "outscale_vpn_connection" "VPN_Secours-NET-TEST" {
    client_gateway_id  = outscale_client_gateway.CGW_Celeste-NET-TEST.client_gateway_id
    virtual_gateway_id = outscale_virtual_gateway.VGW-NET-TEST.virtual_gateway_id
    connection_type    = "ipsec.1"
    static_routes_only = true
    tags {
        key   = "Name"
        value = "VPN-CLG2-Celeste-TO-NET-TEST"
    }
    depends_on = [outscale_client_gateway.CGW_Celeste-NET-TEST, outscale_virtual_gateway.VGW-NET-TEST]
}

resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST" {
    vpn_connection_id    = outscale_vpn_connection.VPN_Secours-NET-TEST.vpn_connection_id
    destination_ip_range = "10.0.0.0/8"
    depends_on = [ outscale_vpn_connection.VPN_Secours-NET-TEST ]

}

resource "outscale_vpn_connection_route" "VPN_Secours-ROUTE-NET-TEST_192" {
    vpn_connection_id    = outscale_vpn_connection.VPN_Secours-NET-TEST.vpn_connection_id
    destination_ip_range = "192.168.0.0/16"
    depends_on = [ outscale_vpn_connection.VPN_Secours-NET-TEST ]

}

**Comment by outscale-hmi** [comment]
Hello, 
Can you please report your issue in https://github.com/outscale/terraform-provider-outscale
