### ISSUE TITLE
Cleanup non implemented GetToken call

### ISSUE THREAD

**Issue by jerome-jutteau** [outscale/cloud-provider-osc#60]
**What would you like to be added**:

cloud controller manager is making API calls to `ec2metadata/GetToken` which result of a 404 as this call is not implemented in Outscale.

This could be removed from code

**Why is this needed**:

- cleaner logs
- avoid trying to make API calls for nothing
- less network usage

/kind feature

**Comment by RishiKumarRay** [comment]
Can you tell me where in files, can i find this code?
